# -*- coding: utf-8 -*-
"""Exercícios5PY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vPoBHmFCfVi31bS-U1eBf0pyNoLsmmoL
"""

#EXERCÍCIO 1

for n in range(2,22,2):
    print(n)

#EXERCÍCIO 2

for n in range(2,22,2):
    print(n)

#EXERCÍCIO 3

soma = sum(range(1,101,))
print(soma)

#EXERCÍCIO 4
for n1 in range(5,51,5):
   print(n1)

#EXERCÍCIO 5

name = input('Digite seu nome = ')
print ('Saudações, {}!. Seja muito bem vindo a nosso sistema.]'.format(name))